### ISSUE TITLE
Watch.JS name change has broken your name

### ISSUE THREAD

**Issue by gschmottlach-xse** [azain/electron-window-manager#19]
Recently (two days ago) the Watch.JS developer changed the name of his module to melanke-watchjs. This has broken the require() in index.js. Could you please fix your module to reflect this change?

Thanks. . .

**Comment by tysenmoore-xse** [comment]
This [pull request](https://github.com/azain/electron-window-manager/pull/20) seems to fix the issue--could this get integrated to the master branch?

**Comment by johnking** [comment]
Just tried to use this package and found the same issue. 

Who will do the merge since the pull request was submitted?

**Comment by azain** [comment]
Done

**Comment by tysenmoore-xse** [comment]
Can you also push up an updated npm package as well?

**Comment by azain** [comment]
Sure. done.
