### ISSUE TITLE
Layout and VS Code problem

### ISSUE THREAD

**Issue by RafaMedina** [azain/electron-window-manager#2]
I'm using VS Code.

To be able debug it, i specified a parameter in the launch.json
`"runtimeExecutable": "${workspaceRoot}\\node_modules\\electron-prebuilt\\dist\\electron.exe",`

The problem is with layouts, the add method uses utils.getAppLocalPath() which references to electron-prebuilt path, so when it loads the layout file is not found.
`     'add': function(name, path){
            this.layouts[name] = utils.getAppLocalPath() + path;
        },
`
I comments utils.get... and it works correctly.

**Comment by shrimpwagon** [comment]
@azain If this project isn't going to support VS Code then please close this issue
