### ISSUE TITLE
About sharing data, is there any size limitation? And how have you implemented this?

### ISSUE THREAD

**Issue by kyssproject** [azain/electron-window-manager#21]
Hi,

I have been looking for ways of sharing big amounts of data between electron windows. Your module how does this? Is there any limitation?

Thanks,

**Comment by azain** [comment]
You can try these features and see for yourself whether it's sufficient for what you are trying to accomplish:

- https://github.com/azain/electron-window-manager#class-windowmanagerbridge
- https://github.com/azain/electron-window-manager#class-windowmanagershareddata

**Comment by kyssproject** [comment]
Yes, but I mean, is the data JSON-transformed? Is it stored in a file and read by the other window? Or does it work through IPC communications? But you are right in that it is faster to just try it.

Thanks!
