### ISSUE TITLE
Support Electron Screen

### ISSUE THREAD

**Issue by abeelias** [azain/electron-window-manager#4]
In the renderer / DevTools, window.screen is a reserved DOM property, so writing let {screen} = require('electron') will not work. In our examples below, we use electronScreen as the variable name instead.

As a result...

https://github.com/azain/electron-window-manager/blob/master/index.js#L555

should read...

        const {screen: electronScreen} = require('electron');

Thoughts?

**Comment by shrimpwagon** [comment]
@kaseyhinton  Didn't you fix this issue?

@azain Please close if this is resolved.

**Comment by kaseyhinton** [comment]
@shrimpwagon Yes, this issue is fixed.
