### ISSUE TITLE
Initialize the window without showing it

### ISSUE THREAD

**Issue by sklink** [azain/electron-window-manager#7]
I have a few of my windows hidden until they need to be shown, but they need to run in the background in the meantime.

I'm currently accomplishing that by adding a `hide` parameter to your `Window.prototype.open` function. 

Is this something you would consider adding so that I can deploy with your npm package instead of a modified version?

```
    Window.prototype.open = function(url, hide){
        // If the window is already created
        if(_.isObject(this.object)){
            this.focus();
            return false;
        }

        // Create the window
        this.create(url);

        if (!hide) {
          // Show the window
          this.object.show();
        }
    };
```

**Comment by azain** [comment]
Yeah sure, done

**Comment by sklink** [comment]
Fantastic!  

Can you push the changes to npm? I might have done something wrong but the latest version I get with npm install is 1.0.1.

**Comment by callodacity** [comment]
Yeah, I'm also using a patched version to have this functionality.

When you create a `new BrowserWindow` you can pass in the `show: true/false` option, perhaps **electron-window-manager** could use that option to know when to create the window and keep it hidden?

**Comment by shrimpwagon** [comment]
@azain Close this issue if resolved.
